name: Run linter and tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Run linters
        run: nox -vs lint
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Prepare environment
        run: ./setup-dev.sh
      - name: Run dockerized services
        run: docker compose up -d --wait
      - name: Run migrations
        run: cd app/src && pdm run python manage.py wait_for_database --timeout 120 && pdm run python manage.py migrate
      - name: Run unit tests
        run: nox -vs test
      - name: Stop dockerized services
        if: success() || failure()
        run: docker compose down -v
